### ISSUE TITLE
Version 8.3 is released

### ISSUE THREAD

**Issue by mdeboer** [EugenMayer/docker-image-atlassian-jira#4]
Jira 8.3 has been released, can you update the repo?

**Comment by EugenMayer** [comment]
https://confluence.atlassian.com/jirasoftware/jira-software-release-notes-776821069.html there is no 8.3 yet - could you explain?

**Comment by mdeboer** [comment]
Oh no I see, I was thrown off by their message in the Jira Beta app for iOS, which now requires 8.3 which hasn't been released yet.

https://confluence.atlassian.com/jirakb/app-version-requires-jira-8-3-or-later-error-appears-for-beta-participants-969519671.html

Think it'll be there soon though.

**Comment by mdeboer** [comment]
Version 8.3 is released now! 🎉 

https://confluence.atlassian.com/adminjira/jira-8-3-x-platform-release-notes-974375324.html

**Comment by EugenMayer** [comment]
Well we have a build issue, i guess the installer (bin installer) does require java11 or something

```
Unpacking JRE ...
Starting Installer ...
An error occurred:
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
Error log: /tmp/install4jError8613210956024893645.log
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.install4j.runtime.installer.frontend.GUIHelper.invokeOnEDT(GUIHelper.java:703)
	at com.install4j.runtime.installer.frontend.headless.AbstractHeadlessScreenExecutor.init(AbstractHeadlessScreenExecutor.java:73)
	at com.install4j.runtime.installer.frontend.headless.UnattendedScreenExecutor.<init>(UnattendedScreenExecutor.java:51)
	at com.install4j.runtime.installer.frontend.headless.InstallerUnattendedScreenExecutor.<init>(InstallerUnattendedScreenExecutor.java:10)
	at com.install4j.runtime.installer.Installer.getScreenExecutor(Installer.java:83)
	at com.install4j.runtime.installer.Installer.runInProcess(Installer.java:56)
	at com.install4j.runtime.installer.Installer.main(Installer.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
	at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:62)
Caused by: java.lang.reflect.InvocationTargetException
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1349)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1324)
	at com.install4j.runtime.installer.frontend.GUIHelper.invokeOnEDT(GUIHelper.java:699)
	... 12 more
Caused by: java.lang.NullPointerException
	at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
	at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
	at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
	at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)
	at sun.font.SunFontManager$2.run(SunFontManager.java:431)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.SunFontManager.<init>(SunFontManager.java:376)
	at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at sun.awt.X11FontManager.<init>(X11FontManager.java:57)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at sun.font.SunFontManager.getInstance(SunFontManager.java:250)
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:264)
	at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1113)
	at javax.swing.JComponent.getFontMetrics(JComponent.java:1626)
	at javax.swing.text.WrappedPlainView.updateMetrics(WrappedPlainView.java:318)
	at javax.swing.text.WrappedPlainView.updateChildren(WrappedPlainView.java:297)
	at javax.swing.text.WrappedPlainView.insertUpdate(WrappedPlainView.java:463)
	at javax.swing.plaf.basic.BasicTextUI$RootView.insertUpdate(BasicTextUI.java:1610)
	at javax.swing.plaf.basic.BasicTextUI$UpdateHandler.insertUpdate(BasicTextUI.java:1869)
	at javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:201)
	at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:748)
	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:707)
	at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
	at javax.swing.text.DefaultEditorKit.read(DefaultEditorKit.java:273)
	at javax.swing.JEditorPane.setText(JEditorPane.java:1416)
	at javax.swing.JEditorPane.<init>(JEditorPane.java:290)
	at com.install4j.runtime.installer.frontend.headless.AbstractHeadlessScreenExecutor.createEditorPane(AbstractHeadlessScreenExecutor.java:357)
	at com.install4j.runtime.installer.frontend.headless.AbstractHeadlessScreenExecutor.initFontManager(AbstractHeadlessScreenExecutor.java:309)
	at com.install4j.runtime.installer.frontend.headless.AbstractHeadlessScreenExecutor.access$400(AbstractHeadlessScreenExecutor.java:28)
	at com.install4j.runtime.installer.frontend.headless.AbstractHeadlessScreenExecutor$2.run(AbstractHeadlessScreenExecutor.java:77)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by EugenMayer** [comment]
It seems like actually the bundled JRE is used for that, so it must be something else

**Comment by mdeboer** [comment]
Oh damn, yes they made some JRE changes. Reading the logs it probably has something to do with fonts?

**Comment by EugenMayer** [comment]
fixed, image is building now - yes it was font releated

**Comment by EugenMayer** [comment]
available now https://cloud.docker.com/repository/docker/eugenmayer/jira/tags
